### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by lesad** [redabacha/magnolia-react-editor#74]
Hi, first of all, thx for the great work!

I would love to contribute to this repo and make it work with SSR. May I ask, where the problem lies?
My use-case is SSR using NextJS. The type defintions this repo offers seem well designed and would fit my scenario.

**Comment by redabacha** [comment]
hey @lesad,

i appreciate the enthusiasm and interest, i don't have much time to focus on this repo and i've left the company for which this package was needed by. so just to clarify, this package does fully support ssr when rendering a page outside of the magnolia spa editor, i.e. in your next.js app for users. in the readme when it says it does not support ssr in the spa editor, i was only referring to within magnolia itself.

> May I ask, where the problem lies?

there's not really a problem or blocker for having ssr work inside magnolia, in fact doing ssr for the spa editor might possibly already work in theory (just that i have never personally tried it since i had no use case for it). if you try it out, you may see some unwanted logs on the server as the `Comment` component uses `useLayoutEffect` which will throw a warning during ssr but suppressing that is very easy, see https://github.com/redabacha/magnolia-react-editor/pull/75.

**Comment by lesad** [comment]
Just to let you know, there we some problems mainly with the helper functions (`window` and `document` doesn't exist with SSR) which I was able to monkey-patch. 

Another batch of problems arrous from the use of `templateAnnotations`. I am not able to poinpoint the exact lines because I gave up at that point. One thing for sure, SSR support would require quite an extension to this repo.

I really do like the rewrite from class -> functional and hooks. I will keep you posted if we decide to extend the editor's capability.
